import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { challengeRows, controlGame, createTeam, gameState, leaderboard, resetDemo, scoreFor, statuses, submit, teamByCode, useHint, getDb } from '@/lib/db';
import { isOrganizer, makeOrganizerToken, organizerCookie } from '@/lib/auth';

const json=(data,status=200)=>NextResponse.json(data,{status});
const fail=(e)=>json({error:e.message||'Request failed.'},e.message?.includes('locked')?423:400);
function organizer(){return isOrganizer(cookies().get(organizerCookie())?.value);}
async function body(req){try{return await req.json();}catch{return {};}}
export async function GET(req,{params}){try{const p=params.route.join('/');const u=new URL(req.url);if(p==='state')return json(gameState());if(p==='leaderboard')return json(leaderboard());if(p==='team'){const t=teamByCode(u.searchParams.get('code')?.toUpperCase());if(!t)return json({error:'Team not found.'},404);return json({team:{name:t.name,joinCode:t.join_code},score:scoreFor(t.id),game:gameState(),challenges:statuses(t.id)});}if(p==='organizer/data'){if(!organizer())return json({error:'Unauthorized.'},401);const d=getDb();return json({game:gameState(),leaderboard:leaderboard(),submissions:d.prepare('SELECT s.*,t.name team_name,v.name vulnerability FROM submissions s JOIN teams t ON t.id=s.team_id JOIN vulnerabilities v ON v.id=s.vulnerability_id ORDER BY s.submitted_at DESC').all(),hints:d.prepare('SELECT h.*,t.name team_name,v.name vulnerability FROM hints_used h JOIN teams t ON t.id=h.team_id JOIN vulnerabilities v ON v.id=h.vulnerability_id ORDER BY h.used_at DESC').all()});}return json({error:'Not found.'},404);}catch(e){return fail(e);}}
export async function POST(req,{params}){try{const p=params.route.join('/');const b=await body(req);if(p==='join'){const t=teamByCode(String(b.joinCode||'').toUpperCase());if(!t||t.name.toLowerCase()!==String(b.name||'').trim().toLowerCase())throw Error('Team name and join code do not match.');return json({joinCode:t.join_code});}if(p==='submit'){const t=teamByCode(String(b.code||'').toUpperCase());if(!t)throw Error('Team not found.');return json(submit(t.id,b));}if(p==='hint'){const t=teamByCode(String(b.code||'').toUpperCase());if(!t)throw Error('Team not found.');return json(useHint(t.id,Number(b.vulnerabilityId),Number(b.tier)));}if(p==='organizer/login'){if(!process.env.ORGANIZER_PASSCODE)throw Error('ORGANIZER_PASSCODE is not configured.');if(String(b.passcode||'')!==process.env.ORGANIZER_PASSCODE)return json({error:'Incorrect passcode.'},401);const r=json({ok:true});r.cookies.set(organizerCookie(),makeOrganizerToken(),{httpOnly:true,sameSite:'strict',path:'/',secure:process.env.NODE_ENV==='production',maxAge:60*60*12});return r;}if(!organizer())return json({error:'Unauthorized.'},401);if(p==='organizer/team')return json(createTeam(b.name));if(p==='organizer/timer')return json(controlGame(b.action));if(p==='organizer/quality'){const n=Number(b.qualityBonus);if(!Number.isInteger(n)||n<0||n>20)throw Error('Quality bonus must be an integer from 0 to 20.');getDb().prepare('UPDATE submissions SET quality_bonus=? WHERE id=?').run(n,Number(b.submissionId));return json({ok:true});}if(p==='organizer/reset'){if(b.confirm!==true)throw Error('Confirmation is required.');resetDemo();return json({ok:true});}return json({error:'Not found.'},404);}catch(e){return fail(e);}}
